apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vsphere-capacity-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vsphere-capacity-manager
subjects:
  - kind: ServiceAccount
    name: vsphere-capacity-manager
    namespace: vsphere-infra-helpers
