apiVersion: v1
kind: Service
metadata:
  labels:
    app: vsphere-capacity-manager
  name: metrics
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vsphere-capacity-manager
